config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'import/batches#index'

  get(
    '/entity_typeahead',
    :as => :entity_typeahead,
    :to => 'entity_typeahead#index')
  get(
    '/product_typeahead',
    :as => :product_typeahead,
    :to => 'product_typeahead#index')
  get(
    '/unit_of_measure_typeahead',
    :as => :unit_of_measure_typeahead,
    :to => 'unit_of_measure_typeahead#index')
  put(
    '/import/batch/:id/process',
    :as => :process_import_batch,
    :to => 'import/batch/process#update')

  namespace :import do
    resources :batches
  end
  resources :entities
  resources :entity_translations
  resources :price_translations
  resources :products
  resources :product_translations
  resources :purchase_orders do
    resources(
      :lines,
      :controller => 'purchase_order/lines',
      :only => [:create, :new])
  end
  resources(
    :purchase_order_lines,
    :controller => 'purchase_order/lines',
    :only => [:edit, :destroy, :show, :update])
  resources :quantity_translations
  resources :unit_of_measures
  resources :unit_of_measure_translations
end

app/models/product_translation.rb
# Translation class representing the mapping between a CovalentWorks
# source value and a Product.
#
# Uses the sender value to scope the source field and value.
#
# Currently limited to a single source field and value, not sure if a 
# Covalent file would use more than one field.
class ProductTranslation < ActiveRecord::Base
  include FieldTranslation

  belongs_to :product

  validates_presence_of :product
  validates_presence_of :source_field
  validates_presence_of :source_value

  def get_value(*)
    product
  end

  def match?(hash)
    hash[source_field.to_sym] == source_value
  end
end

app/controllers/product_translations_controller.rb
class ProductTranslationsController < ApplicationController
  respond_to(:html)

  def create
    @product_translation = ProductTranslation.new(translation_params).decorate

    if @product_translation.save
      notice_redirect(
        @product_translation, 
        'Translation created successfully', 
        [@product_translation])
    else
      respond_with(@product_translation)
    end
  end

  def index
    # TODO: Implement Ransack searching
    @product_translations = ProductTranslation.all.decorate
  end

  def new
    @product_translation = ProductTranslation.new.decorate
  end

  protected

  def translation_params
    params.
      require(:product_translation).
      permit(
        :product_id,
        :sender_value,
        :source_field,
        :source_value)
  rescue ActionController::ParameterMissing
    {}
  end

end

app/views/product_translations/_form.html.erb
<%= content_for :scripts do %>
<script>
  var product_source = new Bloodhound({
    datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: '<%= product_typeahead_path %>.json?q=%QUERY'
  });
   
  product_source.initialize();
   
  $('.typeahead').typeahead(null, {
    name: 'product-typeahead',
    displayKey: 'name',
    source: product_source.ttAdapter()
  }).
  on('typeahead:selected', function($e, datum) { $('input[id*=product_id]').val(datum.id); });
  on('typeahead:autocompleted', function($e, datum) { $('input[id*=product_id]').val(datum.id); });
</script>
<% end %>
<%= render :partial => '/model_errors', :locals => { :model => model } if model.errors.any? %>

<%= form.input :product_id, :as => :hidden, :controls_html => { class: 'col-sm-4' } %>
<%= form.input :product_display_string, 
  :label => 'Product',
  :controls_html => { class: 'col-sm-4' }, 
  :input_html => { :class => 'typeahead', :placeholder => 'Start typing to find a Product' } %>
<%= form.input :sender_value, :controls_html => { class: 'col-sm-4' } %>
<%= form.input :source_field, :controls_html => { class: 'col-sm-4' } %>
<%= form.input :source_value, :controls_html => { class: 'col-sm-4' } %>

app/views/product_translations/index.html.erb
<table class="table table-striped table-with-link-column">
  <thead>
  <tr>
    <th>Sender</th>
    <th colspan="2">Source</th>
    <th>Product</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% if @product_translations.each do |product_translation| %>
    <tr>
      <td><%= product_translation.sender_value %></td>
      <td><%= product_translation.source_field %></td>
      <td><%= product_translation.source_value %></td>
      <td nowrap><%= product_translation.product_display_string %></td>
      <td nowrap>              
        <%= link_to [product_translation, :return_url => return_url(request.original_url)],
                    class: 'btn btn-default btn-icon btn-sm hidden-print' do %>
            <span class="glyphicon glyphicon-eye-open"></span>
        <% end %>
      </td>
    </tr>
  <% end.empty? %>
    <tr>
      <td colspan="4">No product translations found</td><td></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/product_translations/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= simple_form_for(@product_translation,
                        :defaults => {
                                :input_html => { :class => 'form-control' },
                                :label_html => { :class => 'col-sm-offset-2 col-sm-2' }
                        },
                        :wrapper => :horizontal_form,
                        :wrapper_mappings => {
                                :check_boxes => :horizontal_radio_and_checkboxes,
                                :radio_buttons => :horizontal_radio_and_checkboxes,
                                :file => :horizontal_file_input,
                                :boolean => :horizontal_boolean
                        },
                        :html => { :class => 'form-horizontal' }) do |f| %>
        <div class="page-header">
          <h3>New Product Translation<small></small>
        <span class="pull-right">
          <input type="submit" class="btn btn-primary" value="Save" />
          <%= link_to 'Cancel', product_translations_path(), class: 'btn btn-default' %>
        </span>
          </h3>
        </div>

        <%= render :partial => 'form', :locals => { :form => f, :model => @product_translation } %>
    <% end %>
  </div>
</div>