config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'import/batches#index'

  get(
    '/entity_typeahead',
    :as => :entity_typeahead,
    :to => 'entity_typeahead#index')
  get(
    '/product_typeahead',
    :as => :product_typeahead,
    :to => 'product_typeahead#index')
  get(
    '/unit_of_measure_typeahead',
    :as => :unit_of_measure_typeahead,
    :to => 'unit_of_measure_typeahead#index')
  put(
    '/import/batch/:id/process',
    :as => :process_import_batch,
    :to => 'import/batch/process#update')

  namespace :import do
    resources :batches
  end
  resources :entities
  resources :entity_translations
  resources :price_translations
  resources :products
  resources :product_translations
  resources :purchase_orders do
    resources(
      :lines,
      :controller => 'purchase_order/lines',
      :only => [:create, :new])
  end
  resources(
    :purchase_order_lines,
    :controller => 'purchase_order/lines',
    :only => [:edit, :destroy, :show, :update])
  resources :quantity_translations
  resources :unit_of_measures
  resources :unit_of_measure_translations
end

app/models/product.rb
# Product class representing a tradable product.
class Product < ActiveRecord::Base
  symbolize :source

  validates_presence_of :display_name
  validates_presence_of :name
  validates_presence_of :reference
  validates_presence_of :source
  validates_presence_of :uuid

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  respond_to(:html)

  def create
    context = CreateProduct.call(product_params)

    if context.success?
      notice_redirect(context.product, context.message, [context.product])
    else
      respond_with(@product = context.product)
    end 
  end

  def index
    # TODO: Implement Ransack search
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  protected

  def product_params
    params.
      require(:product).
      permit(
        :name, 
        :display_name, 
        :reference)
  end
end

app/views/products/_form.html.erb
<% if model.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4 class="alert-heading">
        <% if local_assigns.has_key?(:error_message) && error_message %>
        <%= error_message %>
        <% else %>
        <%= pluralize(model.errors.count, 'error') %> prohibited the item from being changed:
        <% end %>
      </h4>
      <ul>
        <% model.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form.input :name, :controls_html => { class: 'col-sm-4' } %>
<%= form.input :display_name, :controls_html => { class: 'col-sm-4' } %>
<%= form.input :reference, :controls_html => { class: 'col-sm-4' } %>

app/views/products/index.html.erb
<table class="table table-striped table-with-link-column">
  <thead>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% if @products.each do |product| %>
    <tr>
      <td nowrap><%= product.name %></td>
      <td nowrap>              
        <%= link_to [product, :return_url => return_url(request.original_url)],
                    class: 'btn btn-default btn-icon btn-sm hidden-print' do %>
            <span class="glyphicon glyphicon-eye-open"></span>
        <% end %>
      </td>
    </tr>
  <% end.empty? %>
    <tr>
      <td colspan="2">No products found</td><td></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= simple_form_for(@product,
                        :defaults => {
                                input_html: { class: 'form-control' },
                                label_html: { class: 'col-sm-offset-2 col-sm-2' }
                        },
                        :wrapper => :horizontal_form,
                        wrapper_mappings: {
                                check_boxes: :horizontal_radio_and_checkboxes,
                                radio_buttons: :horizontal_radio_and_checkboxes,
                                file: :horizontal_file_input,
                                boolean: :horizontal_boolean
                        },
                        :html => { :class => 'form-horizontal' }) do |f| %>
        <div class="page-header">
          <h3>New Product<small></small>
        <span class="pull-right">
          <input type="submit" class="btn btn-primary" value="Save" />
          <%= link_to 'Cancel', products_path(), class: 'btn btn-default' %>
        </span>
          </h3>
        </div>

        <%= render partial: 'form', locals: { form: f, model: @product } %>
    <% end %>
  </div>
</div>